### ISSUE TITLE
some functions are not finished yet

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/python-wechaty-puppet-hostie#13]
There are some function are not finished yet

- [room_search](https://github.com/wechaty/python-wechaty-puppet-hostie/blob/master/src/wechaty_puppet_hostie/puppet.py#L561)
- [room_invitation_accept](https://github.com/wechaty/python-wechaty-puppet-hostie/blob/master/src/wechaty_puppet_hostie/puppet.py#L583)
- [contact_self_name](https://github.com/wechaty/python-wechaty-puppet-hostie/blob/master/src/wechaty_puppet_hostie/puppet.py#L597)
- [contact_signature](https://github.com/wechaty/python-wechaty-puppet-hostie/blob/master/src/wechaty_puppet_hostie/puppet.py#L604)

Welcome to contribute the pr.

**Comment by huangaszaq** [comment]
@wj-Mcat Thanks to figure it out，there are some bots that depend on them.
