### ISSUE TITLE
[New Feature]Add grpc.default_authority option for authorization

### ISSUE THREAD

**Issue by jcai** [wechaty/python-wechaty-puppet-hostie#35]
I want to use  `grpc.default_authority` to identify the current user.Could we add `grpc.default_authority` option to gRPC channel?

see:
https://github.com/wechaty/wechaty-puppet-hostie/pull/78
https://github.com/wechaty/go-wechaty/issues/69
https://github.com/wechaty/java-wechaty/issues/77

**Comment by jcai** [comment]
options = (('grpc.default_authority', token),)

**Comment by wj-Mcat** [comment]
In python grpclib tools, you need to feed `auth_token` to the metadata. refer to : [grpclib client auth](https://grpclib.readthedocs.io/en/latest/metadata.html?highlight=auth#client-side). 

Can you read from the metadata ?

**Comment by jcai** [comment]
Use  channel option,not  metadata

**Comment by jcai** [comment]
refer: https://stackoverflow.com/questions/48170761/how-do-i-specify-server-options

**Comment by wj-Mcat** [comment]
Yes, adding option to channel is simple, but there are some incompatibility problems between `betterproto`、 `grpclib` and `grpcio`. 

- `grpcio` is the google official lib, but can't support `betterproto`. @huan   refer to : [
Better Python support by integrating python-betterproto ](https://github.com/grpc/grpc/issues/24110) 
to address this problem, we should replace betterproto with grpcio. 
- `grpclib` can custom options, refer to: [Can the channel carry options？](https://github.com/vmagamedov/grpclib/issues/98)
 this lib is not active, I think we should replace it with grpcio.

**Comment by wj-Mcat** [comment]
Find a trick solution:
```python
import asyncio

from chatie_grpc.wechaty import PuppetStub
from grpclib.client import Channel


async def main():
    target = "server-address:port"
    channel = Channel(host="server-address", port=port)
    # this is the private field 
    channel._authority = "your-token"
    sub = PuppetStub(channel)
    await sub.start()
    print("started ...")
    async for response in sub.event():
        print(response)

asyncio.run(main())
```

output: 
```text
started ...
EventResponse(type=22, payload='{"qrcode":"http://weixin.qq.com/x/I7He3Ou3_pzXqJFzAQ5M","status":2}')
EventResponse(type=22, payload='{"data":"{\\"status\\":\\"Waiting\\"}","status":2}')
EventResponse(type=22, payload='{"data":"{\\"status\\":\\"Waiting\\"}","status":2}')
```

this works for me.
